---
AgentId: "3010040"
Secret: "Ldys9cD8SqpPiePYEaNQqOf-4i1vX_OabNJ8qEsrtCA"
corpid: "wwa90325ed46addba3"
contactSecret: "7gPOADnNRysIkwhO3br0IGjp_9ekuuZiwLsa4WvUaB4"

current: test
env:
  dev:
    "qyapi.weixin.qq.com": "qyapi.weixin.qq.com"
  test:
    "qyapi.weixin.qq.com": "140.207.127.79"